use crate::core::error::{CoreError, CoreResult};
use crate::core::filesystem::config::{ConduitConfig, InstanceType};
use crate::core::filesystem::lock::ConduitLock;
use crate::core::paths::CorePaths;
use std::collections::BTreeMap;
use std::fs;

impl ConduitLock {
    pub fn load_config(paths: &CorePaths) -> CoreResult<ConduitConfig> {
        let config_content =
            fs::read_to_string(paths.config_path()).map_err(|_| CoreError::MissingConfig)?;
        Ok(serde_json::from_str(&config_content)?)
    }

    pub fn save_config(paths: &CorePaths, config: &ConduitConfig) -> CoreResult<()> {
        fs::write(paths.config_path(), serde_json::to_string_pretty(config)?)?;
        Ok(())
    }

    pub fn load_lock(paths: &CorePaths) -> CoreResult<ConduitLock> {
        let content = fs::read_to_string(paths.lock_path()).ok();
        if let Some(c) = content
            && let Ok(lock) = toml::from_str(&c)
        {
            return Ok(lock);
        }

        Ok(ConduitLock {
            version: 1,
            locked_mods: std::collections::HashMap::new(),
            loader_version: None,
        })
    }

    #[rustfmt::skip]
    pub fn save_lock(paths: &CorePaths, lock: &ConduitLock) -> CoreResult<()> {
        let mut content = String::new();

        content.push_str("# ---------------------------------------------------------------------------- #\n");
        content.push_str("#                                                                              #\n");
        content.push_str("#                       THIS FILE IS AUTOMATICALLY GENERATED                   #\n");
        content.push_str("#                            DO NOT EDIT THIS FILE MANUALLY                    #\n");
        content.push_str("#                                                                              #\n");
        content.push_str("# ---------------------------------------------------------------------------- #\n");
        content.push_str("#                                                                              #\n");
        content.push_str("#  This file contains the precise reproduction information for the project's   #\n");
        content.push_str("#  dependencies. Editing it could break your environment synchronization.      #\n");
        content.push_str("#                                                                              #\n");
        content.push_str("# ---------------------------------------------------------------------------- #\n\n");

        content.push_str(&toml::to_string_pretty(lock)?);

        fs::write(paths.lock_path(), content)?;
        Ok(())
    }
}

impl Default for ConduitConfig {
    fn default() -> Self {
        Self {
            name: "conduit-server".to_string(),
            instance_type: InstanceType::Server,
            mc_version: "1.21.1".to_string(),
            loader: "neoforge@latest".to_string(),
            mods: BTreeMap::new(),
        }
    }
}
