use crate::core::error::{CoreError, CoreResult};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum ModSide {
    Server,
    Client,
    Both,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct ConduitLock {
    pub version: i32,
    pub conduit_version: String,
    pub locked_mods: HashMap<String, LockedMod>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub loader: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LockedMod {
    pub id: String,
    pub version_id: String,
    pub filename: String,
    pub url: String,
    pub hash: String,
    pub side: ModSide,
    pub dependencies: Vec<String>,
}

impl ConduitLock {
    pub fn is_mod_installed(&self, slug: &str) -> bool {
        self.locked_mods.contains_key(slug)
    }

    pub fn from_toml(content: &str) -> CoreResult<Self> {
        toml::from_str(content)
            .map_err(|e| CoreError::RuntimeError(format!("Failed to parse conduit.lock: {e}")))
    }

    #[rustfmt::skip]
    pub fn to_toml_with_header(&self) -> CoreResult<String> {
        let mut content = String::new();

        content.push_str("# ---------------------------------------------------------------------------- #\n");
        content.push_str("#                                                                              #\n");
        content.push_str("#                       THIS FILE IS AUTOMATICALLY GENERATED                   #\n");
        content.push_str("#                            DO NOT EDIT THIS FILE MANUALLY                    #\n");
        content.push_str("#                                                                              #\n");
        content.push_str("# ---------------------------------------------------------------------------- #\n");
        content.push_str("#                                                                              #\n");
        content.push_str("#  This file contains the precise reproduction information for the project's   #\n");
        content.push_str("#  dependencies. Editing it could break your environment synchronization.      #\n");
        content.push_str("#                                                                              #\n");
        content.push_str("# ---------------------------------------------------------------------------- #\n\n");

        let serialized = toml::to_string_pretty(self).map_err(|e| {
            CoreError::RuntimeError(format!("Failed to serialize lock: {e}"))
        })?;

        content.push_str(&serialized);
        Ok(content)
    }
}

impl Default for ConduitLock {
    fn default() -> Self {
        Self {
            version: 1,
            conduit_version: env!("CARGO_PKG_VERSION").to_string(),
            locked_mods: HashMap::new(),
            loader: None,
        }
    }
}
