use serde::{Deserialize, Serialize};

use crate::config::ConduitConfig;
use crate::core::error::{CoreError, CoreResult};
use crate::core::paths::CorePaths;
use std::collections::HashMap;
use std::fs;

#[derive(Serialize, Deserialize, Debug)]
pub struct ConduitLock {
    pub version: i32,
    pub locked_mods: HashMap<String, LockedMod>,
    pub loader_version: String,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct LockedMod {
    pub id: String,
    pub version_id: String,
    pub filename: String,
    pub url: String,
    pub hash: String,
    pub dependencies: Vec<String>,
}

impl ConduitLock {
    pub fn load_config(paths: &CorePaths) -> CoreResult<ConduitConfig> {
        let config_content =
            fs::read_to_string(paths.config_path()).map_err(|_| CoreError::MissingConfig)?;
        Ok(serde_json::from_str(&config_content)?)
    }

    pub fn save_config(paths: &CorePaths, config: &ConduitConfig) -> CoreResult<()> {
        fs::write(paths.config_path(), serde_json::to_string_pretty(config)?)?;
        Ok(())
    }

    pub fn load_lock(paths: &CorePaths) -> CoreResult<ConduitLock> {
        let content = fs::read_to_string(paths.lock_path()).ok();
        if let Some(c) = content
            && let Ok(lock) = toml::from_str(&c)
        {
            return Ok(lock);
        }

        Ok(ConduitLock {
            version: 1,
            locked_mods: std::collections::HashMap::new(),
            loader_version: String::from("219"),
        })
    }

    #[rustfmt::skip]
    pub fn save_lock(paths: &CorePaths, lock: &ConduitLock) -> CoreResult<()> {
        let mut content = String::new();

        content.push_str("# ---------------------------------------------------------------------------- #\n");
        content.push_str("#                                                                              #\n");
        content.push_str("#                       THIS FILE IS AUTOMATICALLY GENERATED                   #\n");
        content.push_str("#                            DO NOT EDIT THIS FILE MANUALLY                    #\n");
        content.push_str("#                                                                              #\n");
        content.push_str("# ---------------------------------------------------------------------------- #\n");
        content.push_str("#                                                                              #\n");
        content.push_str("#  This file contains the precise reproduction information for the project's   #\n");
        content.push_str("#  dependencies. Editing it could break your environment synchronization.      #\n");
        content.push_str("#                                                                              #\n");
        content.push_str("# ---------------------------------------------------------------------------- #\n\n");

        content.push_str(&toml::to_string_pretty(lock)?);

        fs::write(paths.lock_path(), content)?;
        Ok(())
    }
}
