use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs;

#[derive(Serialize, Deserialize, Debug)]
pub struct ConduitLock {
    pub version: i32,
    pub locked_mods: HashMap<String, LockedMod>,
}

#[derive(Serialize, Deserialize, Debug)]
pub struct LockedMod {
    pub id: String,
    pub version_id: String,
    pub filename: String,
    pub url: String,
    pub hash: String,
    pub dependencies: Vec<String>,
}

impl ConduitLock {
    pub fn load() -> Self {
        fs::read_to_string("conduit.lock")
            .ok()
            .and_then(|content| toml::from_str(&content).ok())
            .unwrap_or_else(|| ConduitLock {
                version: 1,
                locked_mods: HashMap::new(),
            })
    }
    
    #[rustfmt::skip]
    pub fn save(&self) -> Result<(), Box<dyn std::error::Error>> {
        let mut content = String::new();

        content.push_str("# ---------------------------------------------------------------------------- #\n");
        content.push_str("#                                                                              #\n");
        content.push_str("#                       THIS FILE IS AUTOMATICALLY GENERATED                   #\n");
        content.push_str("#                            DO NOT EDIT THIS FILE MANUALLY                    #\n");
        content.push_str("#                                                                              #\n");
        content.push_str("# ---------------------------------------------------------------------------- #\n");
        content.push_str("#                                                                              #\n");
        content.push_str("#  This file contains the precise reproduction information for the project's   #\n");
        content.push_str("#  dependencies. Editing it could break your environment synchronization.      #\n");
        content.push_str("#                                                                              #\n");
        content.push_str("# ---------------------------------------------------------------------------- #\n\n");

        content.push_str(&toml::to_string_pretty(self)?);

        fs::write("conduit.lock", content)?;
        Ok(())
    }
}
